---
title: "Variation in stress tolerance in Queensland fruit fly"
subtitle: "Statitics analysis cold tolerance"
author: Popa-Baez A. D., Lee S. F., Yeap H. L., Prasad S. S., Schiffer M., Mourant
  R., Castro-Vargas C., Edwards O. R., Taylor P. W. and Oakeshott J. G.
date: "20 April 2019"
output: html_document
---


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
knitr::opts_chunk$set(echo=FALSE, 
               warning=FALSE, message=FALSE)

source("./R/cold_data_import_and_cleaning.R")
```


#### **Wild:**


** Is there population differences in wild populations?**

```{r population differences wild cold Males, echo=FALSE, warning=FALSE}

xtable(anova(glm(rtime ~ pop, data = cold.wild.s[[2]], family = Gamma(link = "log")), test = "Chisq")) %>% 
  knitr::kable(digits = 5, caption = "Analisys of deviance difference in cold tolerance wild Qfly males" )

```


#### **Domesticated:**

**Are there population differences in domesticated populations?**

```{r population differences old cold Males, message=FALSE, warning=FALSE }


xtable(anova(glm(rtime ~ pop, data = cold.old.s[[2]], family = Gamma(link = "log")), test = "Chisq")) %>% 
  knitr::kable(digits = 3, caption = "Analisys of deviance difference in cold tolerance domesticated Qfly males" )

```

```{r population differences in cold tolerance wild vs domesticated males}

cold.trt.p.3.domes <- cold.trt.p.3 %>% 
  filter(!pop %in% c("Bega Valley", "Canberra", "Cape Tribulation")) %>% 
  filter(sex== "Male") %>% droplevels()


xtable(anova(glm(rtime ~ pop + status + pop*status, data = cold.trt.p.3.domes, family = Gamma(link = "log")), test = "Chisq")) %>% 
  `rownames<-`(c("NULL", "Population", "Domestication Status", "Population * Domestication Status")) %>%
  knitr::kable(digits = 3, 
               caption = "Analysis of deviance table comparison of cold tolerance in Qfly males for wild and domesticated populations")


glm.cold.domes <- glm(rtime ~ pop + status + pop*status, data = cold.trt.p.3.domes, family = Gamma(link = "log"))

```
